src/main/java/org/D7noun/view/FileBean.java
package org.D7noun.view;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

import javax.annotation.Resource;
import javax.ejb.EJB;
import javax.ejb.SessionContext;
import javax.ejb.Stateful;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.event.PhaseId;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Join;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import org.D7noun.model.Attachment;
import org.D7noun.model.File;
import org.D7noun.model.File.Sex;
import org.D7noun.model.MedicalHistory;
import org.D7noun.model.Settings;
import org.D7noun.model.Settings.SettingType;
import org.D7noun.model.Treatment;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.omnifaces.util.Faces;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.UploadedFile;

/**
 * Backing bean for File entities.
 * <p/>
 * This class provides CRUD functionality for all File entities. It focuses
 * purely on Java EE 6 standards (e.g. <tt>&#64;ConversationScoped</tt> for
 * state management, <tt>PersistenceContext</tt> for persistence,
 * <tt>CriteriaBuilder</tt> for searches) rather than introducing a CRUD
 * framework or custom base class.
 */

@Named
@Stateful
@ConversationScoped
public class FileBean implements Serializable {

	/**
	 * 
	 * D7noun Start
	 * 
	 */

	@EJB
	private SettingsFacade settingsFacade;

	private boolean male;
	private Long fileIdForTreatments;

	private boolean sixMonthsPatients = false;

	private File fileForDelete;

	public File getFileForDelete() {
		return fileForDelete;
	}

	public void setFileForDelete(File fileForDelete) {
		this.fileForDelete = fileForDelete;
	}

	public List<Settings> getAllDoctorNames() {
		try {
			return settingsFacade.findSettingByType(SettingType.DOCTOR);
		} catch (Exception e) {
			System.err.println("D7noun: get all doctor names");
			e.printStackTrace();
		}
		return new ArrayList<>();
	}

	public void selectForDelete(File f) {
		fileForDelete = f;
	}

	/**
	 * 
	 * D7noun End
	 * 
	 */

	private static final long serialVersionUID = 1L;

	/*
	 * Support creating and retrieving File entities
	 */

	private Long id;

	// D7noun: This attribute is used for searching only
	private String drName;

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	private File file;

	public File getFile() {
		return this.file;
	}

	public void setFile(File file) {
		this.file = file;
	}

	@Inject
	private Conversation conversation;

	@PersistenceContext(unitName = "clinic-pu", type = PersistenceContextType.EXTENDED)
	private EntityManager entityManager;

	public String create() {
		this.conversation.begin();
		this.conversation.setTimeout(1800000L);
		return "create?faces-redirect=true";
	}

	public File save(File file) {
		return entityManager.merge(file);
	}

	public void retrieve() {

		if (FacesContext.getCurrentInstance().isPostback()) {
			return;
		}

		if (this.conversation.isTransient()) {
			this.conversation.begin();
			this.conversation.setTimeout(1800000L);
		}

		if (this.id == null) {
			this.file = this.example;
			this.file.setHasRemainingDept(false);
			List<MedicalHistory> medicalHistories = new ArrayList<MedicalHistory>();
			List<Settings> diseases = settingsFacade.findSettingByType(SettingType.DISEASE);
			for (Settings settings : diseases) {
				medicalHistories.add(new MedicalHistory(settings.getValue()));
			}
			this.file.setMedicalHistories(medicalHistories);

		} else {
			this.file = findById(getId());
			if (this.file.getSex() == Sex.MALE) {
				setMale(true);
			} else {
				setMale(false);
			}
		}
	}

	public File findById(Long id) {

		return this.entityManager.find(File.class, id);
	}

	/*
	 * Support updating and deleting File entities
	 */

	public String update() {
		this.conversation.end();

		try {

			if (isMale()) {
				file.setSex(Sex.MALE);
			} else {
				file.setSex(Sex.FEMALE);
			}

			if (this.id == null) {
				this.entityManager.persist(this.file);
				return "create?faces-redirect=true&id=" + this.file.getFileNumber();
			} else {
				this.entityManager.merge(this.file);
				return "create?faces-redirect=true&id=" + this.file.getFileNumber();
			}
		} catch (Exception e) {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
			return null;
		}
	}

	public String delete() {
		this.conversation.end();

		try {
			File deletableEntity = findById(getId());
			this.entityManager.remove(deletableEntity);
			this.entityManager.flush();
			return "search?faces-redirect=true";
		} catch (Exception e) {
			FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
			return null;
		}
	}

	@Resource
	private SessionContext sessionContext;

	public Converter getConverter() {

		final FileBean ejbProxy = this.sessionContext.getBusinessObject(FileBean.class);

		return new Converter() {

			@Override
			public Object getAsObject(FacesContext context, UIComponent component, String value) {

				return ejbProxy.findById(Long.valueOf(value));
			}

			@Override
			public String getAsString(FacesContext context, UIComponent component, Object value) {

				if (value == null) {
					return "";
				}

				return String.valueOf(((File) value).getFileNumber());
			}
		};
	}

	/*
	 * Support searching File entities with pagination
	 */

	private int page;
	private long count;
	private List<File> pageItems;

	private File example = new File();

	public int getPage() {
		return this.page;
	}

	public void setPage(int page) {
		this.page = page;
	}

	public int getPageSize() {
		return 10;
	}

	public File getExample() {
		return this.example;
	}

	public void setExample(File example) {
		this.example = example;
	}

	public String search() {
		this.page = 0;
		return null;
	}

	public String getDrNames(File file) {
		try {
			String drNames = "";
			List<Treatment> treatments = file.getTreatments();
			List<String> distinctDrNameTreatments = new ArrayList<String>();

			if (treatments != null && !treatments.isEmpty()) {
				for (Treatment treatment : treatments) {
					if (treatment.getDrName() != null && !treatment.getDrName().isEmpty()) {
						if (!distinctDrNameTreatments.contains(treatment.getDrName())) {
							distinctDrNameTreatments.add(treatment.getDrName());
						}
					}
				}

				for (String t : distinctDrNameTreatments) {
					drNames += t + ", ";
				}
				if (drNames.length() > 0) {
					return drNames.substring(0, drNames.length() - 2);
				}
			}

		} catch (Exception e) {
			System.err.println("D7noun:getDrNames");
			e.printStackTrace();
		}
		return "";
	}

	public void paginate() {

		CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();

		// Populate this.count

		CriteriaQuery<Long> countCriteria = builder.createQuery(Long.class);
		Root<File> root = countCriteria.from(File.class);
		countCriteria = countCriteria.select(builder.count(root)).where(getSearchPredicates(root));
		this.count = this.entityManager.createQuery(countCriteria).getSingleResult();

		// Populate this.pageItems

		CriteriaQuery<File> criteria = builder.createQuery(File.class).distinct(true);
		root = criteria.from(File.class);
		TypedQuery<File> query = this.entityManager.createQuery(criteria.select(root).where(getSearchPredicates(root)));
		query.setFirstResult(this.page * getPageSize()).setMaxResults(getPageSize());
		this.pageItems = query.getResultList();
	}

	private Predicate[] getSearchPredicates(Root<File> root) {

		CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();
		List<Predicate> predicatesList = new ArrayList<Predicate>();

		String name = this.example.getName();
		boolean hasRemainingDept = this.example.isHasRemainingDept();

		if (name != null && !"".equals(name)) {
			predicatesList.add(builder.like(builder.lower(root.<String>get("name")), '%' + name.toLowerCase() + '%'));
		}

		if (hasRemainingDept == true) {
			predicatesList.add(builder.equal(root.<Boolean>get("hasRemainingDept"), hasRemainingDept));
		}

		if (drName != null && !"".equals(drName)) {
			Join<File, Treatment> join = root.join("treatments");
			Predicate predicate = builder.like(builder.lower(join.<String>get("drName")),
					'%' + drName.toLowerCase() + '%');
			predicatesList.add(predicate);
		}

		return predicatesList.toArray(new Predicate[predicatesList.size()]);
	}

	public List<File> getPageItems() {

		if (this.pageItems != null && !this.pageItems.isEmpty()) {
			if (sixMonthsPatients) {
				for (Iterator<File> iterator = this.pageItems.iterator(); iterator.hasNext();) {
					File file = iterator.next();
					if (!isFileSixMonthAbsent(file)) {

src/main/webapp/resources/scaffold/pageTemplate.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets">

<h:head>
	<title>#{empty pageTitle ? 'Page Title' : pageTitle}</title>
	<link rel="icon" href='#{resource["favicon.ico"]}' />

	<h:outputStylesheet library="plugins"
		name="bootstrap/css/bootstrap.css" />

	<h:outputStylesheet name="font-awesome.min.css" library="css" />

	<h:outputStylesheet name="forge-style-overriden.css" />
	<h:outputStylesheet name="override.css" />

	<h:outputScript library="primefaces" name="jquery/jquery.js"
		target="head" />
	<h:outputScript library="primefaces" name="jquery/jquery-plugins.js"
		target="head" />
</h:head>

<h:body>
	<ui:debug
		rendered="#{facesContext.application.projectStage == 'Development'}" />
	<div class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<h:link id="brandLink" outcome="/file/search.xhtml"
					styleClass="brand">
					<h:outputText value="Welcome to "
						rendered=" #{request.userPrincipal !=null} " />
                    Clinic  <i>SYSTEM</i>
					<h:outputText value=",  #{request.userPrincipal.name}"
						rendered="#{request.userPrincipal !=null} " />
				</h:link>
			</div>
		</div>
	</div>

	<div class="container forgecontainer">
		<div id="navigation">
			<h:link id="homeLink" outcome="/file/search">
				<h:graphicImage styleClass="forge-img"
					value='#{resource["logo.png"]}' alt="clinic" border="0" />
			</h:link>
			<ul>
				<li><h:link outcome="/file/search" value="File" /></li>
				<li><h:link outcome="/appointment/search" value="Appointment" /></li>
				<li><h:link outcome="/expenses" value="Expenses" /></li>
			</ul>
		</div>


		<h:link outcome="/settings" style="float: right;">

			<h:graphicImage value='#{resource["settings.png"]}'
				style="height: 60px; width: 60px;" />
		</h:link>

		<div id="content">
			<h1>
				<ui:insert name="header" />
			</h1>
			<h4 style="color: #ee91ff;">
				<ui:insert name="headerDetails" />
			</h4>
			<h2>
				<ui:insert name="subheader" />
			</h2>

			<ui:insert name="main" />
		</div>
	</div>

	<footer>
		<div id="footer-wrapper">
			<p>
				<I>Powered by D7noun</I>
			</p>
			<p>D7nounSystem@gmail.com</p>
			<p>9613072121</p>
		</div>
	</footer>

</h:body>
</html>

src/main/webapp/resources/scaffold/paginator.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:ui="http://java.sun.com/jsf/facelets">
	
	<h:panelGroup styleClass="paginator" rendered="#{paginatorBean.count gt paginatorBean.pageSize}">
		<!-- Use commandLink, not outputLink, so that search criteria is not lost -->
		<h:commandLink styleClass="btn btn-primary" rendered="#{paginatorBean.page gt 0}">
			<f:param name="page" value="#{paginatorBean.page - 1}"/>
			&lt; Previous 
		</h:commandLink>
		<h:outputText styleClass="paginator-content" value="#{paginatorBean.page * paginatorBean.pageSize + 1} to #{paginatorBean.page * paginatorBean.pageSize + fn:length(paginatorBean.pageItems)} (of #{paginatorBean.count})"/>
		<h:commandLink styleClass="btn btn-primary" rendered="#{(paginatorBean.page + 1) * paginatorBean.pageSize lt paginatorBean.count}">
			<f:param name="page" value="#{paginatorBean.page + 1}"/>
			Next &gt;
		</h:commandLink>
	</h:panelGroup>

</ui:composition>