src/main/java/org/D7noun/model/Attachment.java
package org.D7noun.model;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;

@NamedQueries({
		@NamedQuery(name = Attachment.getAttacmentsByFileId, query = "SELECT attach FROM Attachment attach where attach.file.fileNumber = ?1 ORDER BY attach.size asc"),
		@NamedQuery(name = Attachment.findById, query = "SELECT attach FROM Attachment attach WHERE attach.id = ?1") })
@Entity
public class Attachment implements Serializable {

	/**
	 * 
	 */

	public static final String getAttacmentsByFileId = "Attachment.getAttacmentsByFileId";
	public static final String findById = "Attachment.findById";

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", updatable = false, nullable = false)
	private Long id;

	private String fileName;
	private String contentType;
	private long size;
	private String description;
	private String notes;

	@Lob
	private byte[] data;

	/////////////
	@ManyToOne
	private File file;

	/**
	 * @return the id
	 */
	public Long getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @return the fileName
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * @param fileName the fileName to set
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	/**
	 * @return the contentType
	 */
	public String getContentType() {
		return contentType;
	}

	/**
	 * @param contentType the contentType to set
	 */
	public void setContentType(String contentType) {
		this.contentType = contentType;
	}

	/**
	 * @return the size
	 */
	public long getSize() {
		return size;
	}

	public String getSizeInMegaByte() {
		long fraction = 1024;
		double sizeDouble = size;
		if (size != 0) {
			double sizeFraction = sizeDouble / fraction;
			sizeFraction = Math.floor(sizeFraction * 100) / 100;
			return sizeFraction + " KB";
		}
		return "0 MB";
	}

	/**
	 * @param size the size to set
	 */
	public void setSize(long size) {
		this.size = size;
	}

	/**
	 * @return the data
	 */
	public byte[] getData() {
		return data;
	}

	/**
	 * @param data the data to set
	 */
	public void setData(byte[] data) {
		this.data = data;
	}

	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the notes
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * @param notes the notes to set
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * @return the file
	 */
	public File getFile() {
		return file;
	}

	/**
	 * @param file the file to set
	 */
	public void setFile(File file) {
		this.file = file;
	}

}

src/main/java/org/D7noun/model/File.java
package org.D7noun.model;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.D7noun.abstraction.AbstractEntityWithoutId;

@NamedQueries({
		@NamedQuery(name = File.findAllFilesByTreatmentDrName, query = "SELECT DISTINCT f FROM File f inner join f.treatments t WHERE t.drName = :p1"),
		@NamedQuery(name = File.getAllPhoneNumbers, query = "SELECT DISTINCT f.phoneNumber FROM File f"),
		@NamedQuery(name = File.getMaxAppointmentDateByFileId, query = "SELECT MAX(a.startDate) FROM Appointment a WHERE a.file = :file") })
@Entity
@Table(name = "file")
public class File extends AbstractEntityWithoutId implements Serializable {

	public static final String findAllFilesByTreatmentDrName = "findAllFilesByTreatmentDrName";
	public static final String getAllPhoneNumbers = "getAllPhoneNumbers";
	public static final String getMaxAppointmentDateByFileId = "File.getMaxAppointmentDateByFileId";

	public enum Sex {
		MALE, FEMALE;
	}

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	@Column(name = "id", updatable = false, nullable = false)
	private Long fileNumber;

	@Column(nullable = false)
	private String name;

	@Column
	@Enumerated(EnumType.STRING)
	private Sex sex;

	@Column
	@Temporal(TemporalType.DATE)
	private Date dateOfBirth;

	@Column
	private String address;

	@Column
	private String phoneNumber;

	@Column
	private String occupation;

	@Column
	private boolean hasRemainingDept;

	@Column(length = 1000)
	private String detailsOfPayment;

	@Column(length = 1000)
	private String notes;

	@OneToMany(cascade = CascadeType.ALL, orphanRemoval = true)
	@JoinColumn(name = "file_id")
	private List<MedicalHistory> medicalHistories = new ArrayList<MedicalHistory>();

	@OneToMany(mappedBy = "file", cascade = CascadeType.ALL, orphanRemoval = true)
	private List<Treatment> treatments = new ArrayList<Treatment>();

	@OneToMany(mappedBy = "file", cascade = CascadeType.MERGE, orphanRemoval = true)
	private Set<Attachment> attachments = new HashSet<Attachment>();

	public int getAge() {
		if (dateOfBirth != null) {
			Calendar a = getCalendar(dateOfBirth);
			Calendar b = getCalendar(new Date());
			int diff = b.get(Calendar.YEAR) - a.get(Calendar.YEAR);
			if (a.get(Calendar.MONTH) > b.get(Calendar.MONTH) || (a.get(Calendar.MONTH) == b.get(Calendar.MONTH)
					&& a.get(Calendar.DATE) > b.get(Calendar.DATE))) {
				diff--;
			}
			return diff;
		} else {
			return 0;
		}
	}

	public File addNewTreatment(Treatment treatment) {
		if (treatment != null) {
			this.treatments.add(treatment);
			treatment.setFile(this);
		}
		return this;
	}

	public File removeTreatment(Treatment treatment) {
		if (treatment != null) {
			this.treatments.remove(treatment);
			treatment.setFile(null);
		}
		return this;
	}

	public static Calendar getCalendar(Date date) {
		Calendar cal = Calendar.getInstance(Locale.US);
		cal.setTime(date);
		return cal;
	}

	/**
	 * 
	 * 
	 * 
	 * 
	 * D7noun: Getters And Setters
	 * 
	 * 
	 * 
	 * 
	 * *
	 * 
	 * @return
	 */

	/**
	 * @return the fileNumber
	 */
	public Long getFileNumber() {
		return fileNumber;
	}

	/**
	 * @param fileNumber the fileNumber to set
	 */
	public void setFileNumber(Long fileNumber) {
		this.fileNumber = fileNumber;
	}

	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @param name the name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * @return the sex
	 */
	public Sex getSex() {
		return sex;
	}

	/**
	 * @param sex the sex to set
	 */
	public void setSex(Sex sex) {
		this.sex = sex;
	}

	/**
	 * @return the dateOfBirth
	 */
	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	/**
	 * @param dateOfBirth the dateOfBirth to set
	 */
	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	/**
	 * @return the address
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * @param address the address to set
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * @return the phoneNumber
	 */
	public String getPhoneNumber() {
		return phoneNumber;
	}

	/**
	 * @param phoneNumber the phoneNumber to set
	 */
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	/**
	 * @return the occupation
	 */
	public String getOccupation() {
		return occupation;
	}

	/**
	 * @param occupation the occupation to set
	 */
	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	/**
	 * @return the hasRemainingDept
	 */
	public boolean isHasRemainingDept() {
		return hasRemainingDept;
	}

	/**
	 * @param hasRemainingDept the hasRemainingDept to set
	 */
	public void setHasRemainingDept(boolean hasRemainingDept) {
		this.hasRemainingDept = hasRemainingDept;
	}

	/**
	 * @return the detailsOfPayment
	 */
	public String getDetailsOfPayment() {
		return detailsOfPayment;
	}

	/**
	 * @param detailsOfPayment the detailsOfPayment to set
	 */
	public void setDetailsOfPayment(String detailsOfPayment) {
		this.detailsOfPayment = detailsOfPayment;
	}

	/**
	 * @return the notes
	 */
	public String getNotes() {
		return notes;
	}

	/**
	 * @param notes the notes to set
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}

	/**
	 * @return the treatments
	 */
	public List<Treatment> getTreatments() {
		return treatments;
	}

	/**
	 * @param treatments the treatments to set
	 */
	public void setTreatments(List<Treatment> treatments) {
		this.treatments = treatments;
	}

	/**
	 * @return the attachments
	 */
	public Set<Attachment> getAttachments() {
		return attachments;
	}

	/**
	 * @param attachments the attachments to set
	 */
	public void setAttachments(Set<Attachment> attachments) {
		this.attachments = attachments;
	}

	/**
	 * @return the findallfilesbytreatmentdrname
	 */
	public static String getFindallfilesbytreatmentdrname() {
		return findAllFilesByTreatmentDrName;
	}

	/**
	 * @return the getallphonenumbers
	 */
	public static String getGetallphonenumbers() {
		return getAllPhoneNumbers;
	}

	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public String displayName() {
		return getName() + " | " + getPhoneNumber();
	}

	/**
	 * @return the medicalHistories
	 */
	public List<MedicalHistory> getMedicalHistories() {
		return medicalHistories;
	}

	/**
	 * @param medicalHistories the medicalHistories to set
	 */
	public void setMedicalHistories(List<MedicalHistory> medicalHistories) {
		this.medicalHistories = medicalHistories;
	}
}

src/main/webapp/file/create.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:forgeview="http://jboss.org/forge/view"
	xmlns:p="http://primefaces.org/ui"
	template="/resources/scaffold/pageTemplate.xhtml">

	<f:metadata>
		<f:viewParam name="id" value='#{fileBean.id}' />
		<f:event type="preRenderView" listener='#{fileBean.retrieve}' />
	</f:metadata>

	<ui:param name="pageTitle" value="Create File" />

	<ui:define name="header">
		File
	</ui:define>

	<ui:define name="headerDetails">
		<ui:repeat value="#{fileBean.file.medicalHistories}"
			var="medicalHistory">
			<h:panelGroup rendered="#{medicalHistory.exist}">#{medicalHistory.disease}</h:panelGroup>
		</ui:repeat>
	</ui:define>

	<ui:define name="subheader">
		<c:choose>
			<c:when test='#{!empty fileBean.id}'>
				Edit existing File
			</c:when>
			<c:otherwise>
				Create a new File  
			</c:otherwise>
		</c:choose>
	</ui:define>

	<ui:define name="footer" />

	<ui:define name="main">

		<link rel="stylesheet" type="text/css"
			href="../resources/pages/css/file.css"></link>

		<h:form id="create" prependId="false">
			<h:messages globalOnly="true" styleClass="error" />

			<h:outputStylesheet name="css/attachment.css" />

			<c:choose>
				<c:when test='#{!empty fileBean.id}'>
					<h:link outcome="file-treatments" title="File Appointments"
						styleClass="a-right-arrows">
						<img src="../resources/right-arrow.png" class="right-arrows"></img>
						<f:param name="id" value="#{fileBean.id}" />
					</h:link>
				</c:when>
			</c:choose>

			<div class="row">

				<div class="col-md-6">
					<div class="form-group">
						<div class="row">
							<div class="col-md-4">
								<h:outputLabel styleClass="control-label"
									for="fileBeanFileFileNumber" value="File Number: *" />
							</div>
							<div class="col-md-8">
								<h:inputText id="fileBeanFileFileNumber"
									styleClass="form-control" readonly="true"
									value="#{fileBean.file.fileNumber}" />
								<h:message for="fileBeanFileFileNumber" styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">
							<div class="col-md-4">
								<h:outputLabel styleClass="control-label" for="fileBeanFileName"
									value="Name: *" />
							</div>
							<div class="col-md-8">
								<h:inputText maxlength="250" id="fileBeanFileName"
									styleClass="form-control" required="true"
									requiredMessage="The Name is Empty"
									value="#{fileBean.file.name}" />
								<h:message for="fileBeanFileName" styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">
							<div class="col-md-4">
								<h:outputLabel styleClass="control-label"
									for="fileBeanFileDateOfBirth" value="Date Of Birth:" />
							</div>
							<div class="col-md-8">
								<p:calendar id="fileBeanFileDateOfBirth"
									value="#{fileBean.file.dateOfBirth}" pattern="dd-MM-yyyy">
									<p:ajax update="fileBeanFileAge" />
								</p:calendar>
								<h:message for="fileBeanFileDateOfBirth" styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">
							<div class="col-md-4">
								<h:outputLabel styleClass="control-label" for="fileBeanFileAge"
									value="Age:" />
							</div>
							<div class="col-md-8">
								<h:inputText id="fileBeanFileAge" styleClass="form-control"
									readonly="true" value="#{fileBean.file.age}" />
								<h:message for="fileBeanFileAge" styleClass="error" />
							</div>
						</div>
					</div>
				</div>

				<div class="col-md-6">
					<div class="form-group">
						<div class="row">
							<div class="col-md-4">
								<h:outputLabel styleClass="control-label" for="fileBeanFileSex"
									value="Gender:" />
							</div>
							<div class="col-md-8 genderInputSwitch">
								<p:inputSwitch id="fileBeanFileSex" value="#{fileBean.male}"
									onLabel="Male" offLabel="Female" />
								<h:message for="fileBeanFileSex" styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">
							<div class="col-md-4">
								<h:outputLabel styleClass="control-label"
									for="fileBeanFileAddress" value="Address:" />
							</div>
							<div class="col-md-8">
								<h:inputText maxlength="250" id="fileBeanFileAddress"
									styleClass="form-control" value="#{fileBean.file.address}" />
								<h:message for="fileBeanFileAddress" styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">
							<div class="col-md-4">
								<h:outputLabel styleClass="control-label"
									for="fileBeanFilePhoneNumber" value="Phone Number:" />
							</div>
							<div class="col-md-8">
								<h:inputText maxlength="250" id="fileBeanFilePhoneNumber"
									styleClass="form-control" value="#{fileBean.file.phoneNumber}" />
								<h:message for="fileBeanFilePhoneNumber" styleClass="error" />
							</div>
						</div>
					</div>

					<div class="form-group">
						<div class="row">
							<div class="col-md-4">
								<h:outputLabel styleClass="control-label"
									for="fileBeanFileOccupation" value="Occupation:" />
							</div>
							<div class="col-md-8">
								<h:inputText maxlength="250" id="fileBeanFileOccupation"
									styleClass="form-control" value="#{fileBean.file.occupation}" />
								<h:message for="fileBeanFileOccupation" styleClass="error" />
							</div>
						</div>
					</div>
				</div>

			</div>

			<p:spacer></p:spacer>
			<p:separator></p:separator>

			<div class="col-md-12">
				<ui:repeat value="#{fileBean.file.medicalHistories}"
					var="medicalHistory">
					<div class="form-group">
						<div class="col-md-7">
							<h:outputLabel styleClass="control-label"
								value="#{medicalHistory.disease} ???" />
						</div>
						<div class="col-md-1 questionsInputSwitch">
							<p:inputSwitch onLabel="Yes" offLabel="No"
								value="#{medicalHistory.exist}">
								<p:ajax update="medication" />
							</p:inputSwitch>
						</div>
						<div class="col-md-4">
							<h:inputText id="medication" maxlength="250"
								styleClass="form-control #{medicalHistory.exist? 'border-red' : 'border-blue'}"
								value="#{medicalHistory.medication}" />
						</div>
					</div>
				</ui:repeat>
			</div>

			<p:spacer></p:spacer>
			<p:separator></p:separator>

			<div class="col-md-12">
				<div class="form-group">
					<div class="col-md-2">
						<h:outputLabel for="fileBeanFileDetailsOfPayment"
							value="Details Of Payment:" />
					</div>
					<div class="col-md-10">
						<p:inputTextarea id="fileBeanFileDetailsOfPayment"
							maxlength="1000" styleClass="textArea"
							value="#{fileBean.file.detailsOfPayment}" />
					</div>
				</div>
			</div>

			<div class="col-md-12">
				<div class="form-group">
					<div class="col-md-2">
						<h:outputLabel for="fileBeanFileNotes" value="Notes:" />
					</div>
					<div class="col-md-10">
						<p:inputTextarea id="fileBeanFileNotes" maxlength="1000"
							styleClass="textArea" value="#{fileBean.file.notes}" />
					</div>
				</div>
			</div>


			<p:spacer></p:spacer>
			<p:separator></p:separator>

			<ui:remove>
				<!-- 			<h:panelGroup rendered='#{!empty fileBean.id}'> -->
				<!-- 				<div class="row"> -->
				<!-- 					<div class="col-md-12"> -->
				<!-- 						<p:dataTable id="attachmentsDataTable" widgetVar="attachmentVar" -->
				<!-- 							rows="5" paginator="true" -->
				<!-- 							paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}" -->
				<!-- 							rowsPerPageTemplate="5,10,15,20,50" -->
				<!-- 							paginatorAlwaysVisible="false" paginatorPosition="bottom" -->
				<!-- 							value="#{fileBean.file.attachments}" var="attachment" -->
				<!-- 							rowKey="#{attachment.id}" rowIndexVar="index" editable="true" -->
				<!-- 							editMode="cell"> -->

				<!-- 							<f:facet name="header"> -->

				<!-- 								<h:outputText value="Attachments" -->
				<!-- 									styleClass="attachmentHeaderText" /> -->

				<!-- 								<p:fileUpload widgetVar="fileUploadVar" multiple="true" -->
				<!-- 									auto="true" styleClass="fileUploader hide" -->
				<!-- 									fileUploadListener="#{fileBean.handleFileUpload}" -->
				<!-- 									process="@this" update="attachmentsDataTable" /> -->

				<!-- 								<h:commandLink onclick="$('.fileUploader input').click()" -->
				<!-- 									styleClass="btn btn-primary white attachmentHeaderButton"> -->
				<!-- 									<f:ajax /> -->
				<!-- 									<i class="fa fa-plus white" /> -->
				<!-- 								</h:commandLink> -->

				<!-- 							</f:facet> -->

				<!-- 							<p:column id="index" width="50"> -->
				<!-- 								<h:outputText value="#{index+1}"></h:outputText> -->
				<!-- 							</p:column> -->

				<!-- 							<p:column id="actions" width="50"> -->
				<!-- 								<h:commandLink styleClass="btn btn-sm btn-danger white" -->
				<!-- 									action="#{fileBean.selectForDelete(attachment)}" -->
				<!-- 									onclick="PF('deleteAttachmentDialogVar').show()"> -->
				<!-- 									<i class="fa fa-trash white" /> -->
				<!-- 									<f:ajax /> -->
				<!-- 								</h:commandLink> -->
				<!-- 							</p:column> -->

				<!-- 							<p:column id="attachmentName" headerText="Name" -->
				<!-- 								filterMatchMode="contains" filterBy="#{attachment.fileName}" -->
				<!-- 								sortBy="#{attachment.fileName}" -->
				<!-- 								styleClass="attachmentName-column" width=""> -->
				<!-- 								<h:outputText value="#{attachment.fileName}" -->
				<!-- 									title="#{attachment.fileName}" /> -->
				<!-- 							</p:column> -->

				<!-- 							<p:column id="attachmentSize" headerText="Size" -->
				<!-- 								sortBy="#{attachment.size}" style="text-align: center"> -->
				<!-- 								<h:outputText value="#{attachment.sizeInMegaByte}" -->
				<!-- 									title="#{attachment.sizeInMegaByte}" /> -->
				<!-- 							</p:column> -->

				<!-- 							<p:column id="description" headerText="Description" -->
				<!-- 								filterMatchMode="contains" filterBy="#{attachment.description}" -->
				<!-- 								sortBy="#{attachment.description}" -->
				<!-- 								styleClass="attachmentDescription-column"> -->
				<!-- 								<h:inputText value="#{attachment.description}" -->
				<!-- 									styleClass="form-control" /> -->
				<!-- 							</p:column> -->

				<!-- 							<p:column id="notes" headerText="Notes" -->
				<!-- 								filterMatchMode="contains" filterBy="#{attachment.notes}" -->
				<!-- 								sortBy="#{attachment.notes}" styleClass="attachmentNotes-column"> -->
				<!-- 								<h:inputText value="#{attachment.notes}" -->
				<!-- 									styleClass="form-control" /> -->
				<!-- 							</p:column> -->

				<!-- 							<p:column width="50"> -->
				<!-- 								<h:commandLink action="#{fileBean.download(attachment)}" -->
				<!-- 									styleClass="btn btn-sm btn-primary"> -->
				<!-- 									<i class="fa fa-download white" /> -->
				<!-- 								</h:commandLink> -->

				<!-- 							</p:column> -->

				<!-- 						</p:dataTable> -->
				<!-- 					</div> -->
				<!-- 				</div> -->
				<!-- 			</h:panelGroup> -->
			</ui:remove>

			<div class="buttons">
				<h:commandLink value="Save" action='#{fileBean.update}'
					styleClass="btn btn-success" />
				<c:choose>
					<c:when test='#{!empty fileBean.id}'>
						<h:link value="Cancel" outcome="search"
							styleClass="btn btn-warning" />
						<h:commandLink value="Delete" styleClass="btn btn-danger"
							action="#{fileBean.selectForDelete(treatment)}"
							onclick="PF('deleteDialogVar').show()">
							<f:ajax />
						</h:commandLink>
					</c:when>
					<c:otherwise>
						<h:link value="Cancel" outcome="search"
							styleClass="btn btn-warning" />
					</c:otherwise>
				</c:choose>
			</div>

			<script src="../resources/pages/js/file.js" />

			<p:dialog id="deleteAttachmentDialog" draggable="false"
				closable="false" modal="true" height="50" width="310"
				resizable="false" widgetVar="deleteAttachmentDialogVar">

				<f:facet name="header">
					<h:outputText value="Confirm Deletion????" />
				</f:facet>

				<h:commandLink value="Ok" action="#{fileBean.deleteAttachment()}"
					onclick="PF('deleteAttachmentDialogVar').hide()"
					styleClass="btn btn-sm btn-primary popup-buttons">
					<f:ajax render="attachmentsDataTable" />
				</h:commandLink>
				<h:commandLink value="Cancel"
					styleClass="btn btn-sm btn-danger popup-buttons"
					onclick="PF('deleteAttachmentDialogVar').hide()">
					<f:ajax />
				</h:commandLink>
			</p:dialog>

			<p:dialog id="deleteDialog" draggable="false" closable="false"
				modal="true" height="50" width="300" resizable="false"
				widgetVar="deleteDialogVar">
				<f:facet name="header">
					<h:outputText value="Confirm Deletion????" />
				</f:facet>

				<h:commandLink value="Ok" action="#{fileBean.delete}"
					styleClass="btn btn-primary popup-buttons">
				</h:commandLink>
				<h:commandLink styleClass="btn btn-danger popup-buttons"
					onclick="PF('deleteDialogVar').hide()">
					<h:outputText value="Cancel" />
					<f:ajax />
				</h:commandLink>
			</p:dialog>
		</h:form>
	</ui:define>

</ui:composition>