src/main/java/org/D7noun/model/Appointment.java
package org.D7noun.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.D7noun.abstraction.AbstractEntity;

@NamedQueries(@NamedQuery(name = Appointment.findAppointmentsBetweenTwoDates, query = "SELECT new org.D7noun.dtos.AppointmentDto(a.id,a.startDate, a.endDate,a.file.fileNumber, a.file.name, a.file.phoneNumber, a.drName) FROM Appointment a WHERE a.startDate >= :startDate AND a.endDate <= :endDate"))
@Entity
public class Appointment extends AbstractEntity implements Serializable {

	public static final String findAppointmentsBetweenTwoDates = "Appointment.findAppointmentsBetweenTwoDates";

	private static final long serialVersionUID = 1L;

	@Column
	@Temporal(TemporalType.TIMESTAMP)
	private Date startDate;

	@Column
	@Temporal(TemporalType.TIMESTAMP)
	private Date endDate;

	@ManyToOne(cascade = CascadeType.MERGE)
	private File file;

	@Column(name = "dr_name")
	private String drName;

	public String getDrName() {
		return drName;
	}

	public void setDrName(String drName) {
		this.drName = drName;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (!(obj instanceof Appointment)) {
			return false;
		}
		Appointment other = (Appointment) obj;
		if (id != null) {
			if (!id.equals(other.id)) {
				return false;
			}
		}
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	public File getFile() {
		return this.file;
	}

	public void setFile(final File file) {
		this.file = file;
	}

	public String display() {
		String s = "";
		if (getFile() != null) {
			s += getFile().displayName() + " | ";
		}
		if (getDrName() != null) {
			s += getDrName();
		}
		return s;
	}

	/**
	 * @return the startDate
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * @param startDate the startDate to set
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * @return the endDate
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * @param endDate the endDate to set
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
}

src/main/java/org/D7noun/controller/ExpenseController.java
package org.D7noun.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.D7noun.model.Expense;
import org.D7noun.model.Settings;
import org.D7noun.model.Settings.SettingType;
import org.D7noun.view.ExpenseFacade;
import org.D7noun.view.SettingsFacade;
import org.D7noun.view.TreatmentBean;

@ManagedBean
@ViewScoped
public class ExpenseController implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EJB
	private ExpenseFacade expenseFacade;
	@EJB
	private TreatmentBean treatmentBean;
	@EJB
	private SettingsFacade settingsFacade;
	//////////////////////////////////////

	private Date fromDate;
	private Date toDate;
	//////////////////////////////////////
	private List<Expense> allExpenses = new ArrayList<Expense>();
	private List<Settings> allExpenseKinds = new ArrayList<Settings>();
	private Expense selectExpense;

	/////////////////////////
	/////////////////////////
	/////////////////////////

	@PostConstruct
	public void init() {
		allExpenseKinds = settingsFacade.findSettingByType(SettingType.EXPENSE);
		/////////////////
	}

	public void search() {
		try {
			allExpenses = expenseFacade.FindAllExpensesFromDateToDate(fromDate, toDate);
		} catch (Exception e) {
			System.err.println("D7noun: Search Expenses");
			e.printStackTrace();
		}
	}

	public TreatmentBean getTreatmentBean() {
		return treatmentBean;
	}

	public void setTreatmentBean(TreatmentBean treatmentBean) {
		this.treatmentBean = treatmentBean;
	}

	public SettingsFacade getSettingsFacade() {
		return settingsFacade;
	}

	public void setSettingsFacade(SettingsFacade settingsFacade) {
		this.settingsFacade = settingsFacade;
	}

	public Date getFromDate() {
		return fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public void addNewExpense() {
		Expense expense = new Expense();
		allExpenses.add(expense);
	}

	public void selectExpenseForDelete(Expense expense) {
		selectExpense = expense;
	}

	public void deleteExpense() {
		try {
			if (selectExpense != null) {
				expenseFacade.delete(selectExpense);
				allExpenses.remove(selectExpense);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void save() {
		try {
			expenseFacade.save(allExpenses);
			FacesContext context = FacesContext.getCurrentInstance();
			context.addMessage(null, new FacesMessage("Save Succeeded"));
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public double getExpenseSum() {
		return expenseFacade.getExpenseSum(allExpenses);
	}

	public double getIncome() {
		return treatmentBean.getReceivedSum(fromDate, toDate);
	}

	public double getTotal() {
		return getIncome() - getExpenseSum();
	}

	/**
	 * 
	 * 
	 * 
	 * D7noun
	 * 
	 * 
	 */
	public ExpenseFacade getExpenseFacade() {
		return expenseFacade;
	}

	public void setExpenseFacade(ExpenseFacade expenseFacade) {
		this.expenseFacade = expenseFacade;
	}

	public List<Expense> getAllExpenses() {
		return allExpenses;
	}

	public void setAllExpenses(List<Expense> allExpenses) {
		this.allExpenses = allExpenses;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public Expense getSelectExpense() {
		return selectExpense;
	}

	public void setSelectExpense(Expense selectExpense) {
		this.selectExpense = selectExpense;
	}

	/**
	 * @return the allExpenseKinds
	 */
	public List<Settings> getAllExpenseKinds() {
		return allExpenseKinds;
	}

	/**
	 * @param allExpenseKinds the allExpenseKinds to set
	 */
	public void setAllExpenseKinds(List<Settings> allExpenseKinds) {
		this.allExpenseKinds = allExpenseKinds;
	}

}

src/main/java/org/D7noun/controller/SettingsController.java
package org.D7noun.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.D7noun.model.Settings;
import org.D7noun.model.Settings.SettingType;
import org.D7noun.view.SettingsFacade;
import org.omnifaces.util.Ajax;

@ManagedBean
@ViewScoped
public class SettingsController implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EJB
	private SettingsFacade settingsFacade;

	private List<Settings> doctors = new ArrayList<Settings>();
	private List<Settings> expenses = new ArrayList<Settings>();
	private List<Settings> diseases = new ArrayList<Settings>();
	private List<Settings> treatments = new ArrayList<Settings>();

	private Settings selectForDelete;

	@PostConstruct
	public void init() {
		doctors = settingsFacade.findSettingByType(SettingType.DOCTOR);
		expenses = settingsFacade.findSettingByType(SettingType.EXPENSE);
		diseases = settingsFacade.findSettingByType(SettingType.DISEASE);
		treatments = settingsFacade.findSettingByType(SettingType.TREATMENT);
	}

	public void addDoctor() {
		try {
			Settings settings = new Settings();
			settings.setType(SettingType.DOCTOR);
			doctors.add(settings);
			Ajax.oncomplete("PF('doctorVar').filter()");
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void addExpense() {
		try {
			Settings settings = new Settings();
			settings.setType(SettingType.EXPENSE);
			expenses.add(settings);
			Ajax.oncomplete("PF('expenseVar').filter()");
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void addDisease() {
		try {
			Settings settings = new Settings();
			settings.setType(SettingType.DISEASE);
			diseases.add(settings);
			Ajax.oncomplete("PF('diseaseVar').filter()");
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void addTreatment() {
		try {
			Settings settings = new Settings();
			settings.setType(SettingType.TREATMENT);
			treatments.add(settings);
			Ajax.oncomplete("PF('treatmentVar').filter()");
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void selectForDeleteAction(Settings settings) {
		selectForDelete = settings;
	}

	public void deleteDisease() {
		try {
			if (selectForDelete != null) {
				diseases.remove(selectForDelete);
				settingsFacade.remove(selectForDelete);
				Ajax.oncomplete("PF('diseaseVar').filter()");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void deleteDoctor() {
		try {
			if (selectForDelete != null) {
				doctors.remove(selectForDelete);
				settingsFacade.remove(selectForDelete);
				Ajax.oncomplete("PF('doctorVar').filter()");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void deleteExpense() {
		try {
			if (selectForDelete != null) {
				expenses.remove(selectForDelete);
				settingsFacade.remove(selectForDelete);
				Ajax.oncomplete("PF('expenseVar').filter()");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void deleteTreatment() {
		try {
			if (selectForDelete != null) {
				treatments.remove(selectForDelete);
				settingsFacade.remove(selectForDelete);
				Ajax.oncomplete("PF('treatmentVar').filter()");
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public void save() {
		FacesContext context = FacesContext.getCurrentInstance();
		try {
			settingsFacade.save(diseases);
			settingsFacade.save(expenses);
			settingsFacade.save(doctors);
			settingsFacade.save(treatments);
			context.addMessage(null, new FacesMessage("Save Succeeded"));
		} catch (Exception exception) {
			exception.printStackTrace();
			context.addMessage(null, new FacesMessage("Save Failed"));
		}
	}

	/**
	 * 
	 * D7noun
	 * 
	 */

	public SettingsFacade getSettingsFacade() {
		return settingsFacade;
	}

	public void setSettingsFacade(SettingsFacade settingsFacade) {
		this.settingsFacade = settingsFacade;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
	 * @return the doctors
	 */
	public List<Settings> getDoctors() {
		return doctors;
	}

	/**
	 * @param doctors the doctors to set
	 */
	public void setDoctors(List<Settings> doctors) {
		this.doctors = doctors;
	}

	/**
	 * @return the expenses
	 */
	public List<Settings> getExpenses() {
		return expenses;
	}

	/**
	 * @param expenses the expenses to set
	 */
	public void setExpenses(List<Settings> expenses) {
		this.expenses = expenses;
	}

	/**
	 * @return the diseases
	 */
	public List<Settings> getDiseases() {
		return diseases;
	}

	/**
	 * @param diseases the diseases to set
	 */
	public void setDiseases(List<Settings> diseases) {
		this.diseases = diseases;
	}

	/**
	 * @return the treatments
	 */
	public List<Settings> getTreatments() {
		return treatments;
	}

	/**
	 * @param treatments the treatments to set
	 */
	public void setTreatments(List<Settings> treatments) {
		this.treatments = treatments;
	}

	/**
	 * @return the selectForDelete
	 */
	public Settings getSelectForDelete() {
		return selectForDelete;
	}

	/**
	 * @param selectForDelete the selectForDelete to set
	 */
	public void setSelectForDelete(Settings selectForDelete) {
		this.selectForDelete = selectForDelete;
	}

}

src/main/java/org/D7noun/controller/TreatmentsController.java
package org.D7noun.controller;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import org.D7noun.model.File;
import org.D7noun.model.Treatment;
import org.D7noun.model.Settings.SettingType;
import org.D7noun.view.FileBean;
import org.D7noun.view.SettingsFacade;
import org.D7noun.view.TreatmentBean;

@ManagedBean
@ViewScoped
public class TreatmentsController implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@EJB
	private FileBean fileBean;
	@EJB
	private TreatmentBean treatmentBean;
	@EJB
	private SettingsFacade settingsFacade;

	private String fileId;
	private File file;
	///////////////////////////
	private Treatment treatmentForDelete;
	private List<String> allTreatments = new ArrayList<String>();
	private List<String> allDoctors = new ArrayList<String>();

	public void preRenderViewEvent() {
		if (!FacesContext.getCurrentInstance().isPostback()) {
			if (fileId != null) {
				file = fileBean.findById(Long.parseLong(fileId));
			}
		}
	}

	@PostConstruct
	public void init() {
		try {
			allTreatments = settingsFacade.findSettingValuesByType(SettingType.TREATMENT);
			allDoctors = settingsFacade.findSettingValuesByType(SettingType.DOCTOR);
		} catch (Exception e) {
			e.printStackTrace();
			System.err.println("D7noun: TreatmentController.init");
		}
	}

	public void addTreatment() {
		try {
			Treatment treatment = new Treatment();
			file.addNewTreatment(treatment);
		} catch (Exception exception) {
			exception.printStackTrace();
		}

	}

	public void save() {
		try {
			if (sumBalance() > 0) {
				this.file.setHasRemainingDept(true);
			} else {
				this.file.setHasRemainingDept(false);
			}
			file = fileBean.save(file);
			FacesContext context = FacesContext.getCurrentInstance();
			context.addMessage(null, new FacesMessage("Save Succeeded"));
		} catch (Exception exception) {
			FacesContext context = FacesContext.getCurrentInstance();
			context.addMessage(null, new FacesMessage("Save Failed"));
			exception.printStackTrace();
		}
	}

	public void selectForDelete(Treatment treatment) {
		treatmentForDelete = treatment;
	}

	public void delete() {
		try {
			file.removeTreatment(treatmentForDelete);
			file = fileBean.save(file);
		} catch (Exception exception) {
			exception.printStackTrace();
		}
	}

	// D7noun Summation

	public double sumTotal() {
		double sum = 0;
		if (file != null && !file.getTreatments().isEmpty()) {
			for (Treatment treatment : file.getTreatments()) {
				sum += treatment.getTotal();
			}
		}
		return sum;
	}

	public double sumReceived() {
		double sum = 0;
		if (file != null && !file.getTreatments().isEmpty()) {
			for (Treatment treatment : file.getTreatments()) {
				sum += treatment.getReceived();
			}
		}
		return sum;
	}

	public double sumBalance() {
		double sum = 0;
		if (file != null && !file.getTreatments().isEmpty()) {
			for (Treatment treatment : file.getTreatments()) {
				sum += treatment.getBalance();
			}
		}
		return sum;
	}

	/**
	 * 
	 * 
	 * 
	 * 
	 * 
	 * D7noun: Getters and Setters
	 * 
	 * 
	 * 
	 * 
	 * *
	 */
	/**
	 * @return the fileId
	 */
	public String getFileId() {
		return fileId;
	}

	/**
	 * @param fileId the fileId to set
	 */
	public void setFileId(String fileId) {
		this.fileId = fileId;
	}

	/**
	 * @return the serialversionuid
	 */
	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	/**
	 * @return the file
	 */
	public File getFile() {
		return file;
	}

	/**
	 * @param file the file to set
	 */
	public void setFile(File file) {
		this.file = file;
	}

	/**
	 * @return the fileBean
	 */
	public FileBean getFileBean() {
		return fileBean;
	}

	/**
	 * @param fileBean the fileBean to set
	 */
	public void setFileBean(FileBean fileBean) {
		this.fileBean = fileBean;
	}

	public Treatment getTreatmentForDelete() {
		return treatmentForDelete;
	}

	public void setTreatmentForDelete(Treatment treatmentForDelete) {
		this.treatmentForDelete = treatmentForDelete;
	}

	/**
	 * @return the allTreatments
	 */
	public List<String> getAllTreatments() {
		return allTreatments;
	}

	/**
	 * @param allTreatments the allTreatments to set
	 */
	public void setAllTreatments(List<String> allTreatments) {
		this.allTreatments = allTreatments;
	}

	/**
	 * @return the allDoctors
	 */
	public List<String> getAllDoctors() {
		return allDoctors;
	}

	/**
	 * @param allDoctors the allDoctors to set
	 */
	public void setAllDoctors(List<String> allDoctors) {
		this.allDoctors = allDoctors;
	}
}

src/main/webapp/error.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/resources/scaffold/pageTemplate.xhtml">

	<ui:param name="pageTitle" value="Server error" />

	<ui:define name="header">
		Oops
	</ui:define>

	<ui:define name="subheader">
		That's going to leave a mark!
	</ui:define>

	<ui:define name="main">
		Please Check Your Work!!!!! Or Contact D7noun
	</ui:define>

</ui:composition>

src/main/webapp/expenses.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:forgeview="http://jboss.org/forge/view"
	xmlns:p="http://primefaces.org/ui"
	template="/resources/scaffold/pageTemplate.xhtml">

	<ui:param name="pageTitle" value="Expenses" />

	<ui:define name="header">
		Expenses
	</ui:define>


	<ui:define name="footer" />

	<ui:define name="main">
		<style>
.ui-calendar input, .ui-spinner input {
	width: 100%;
	height: 34px;
	padding: 6px 12px;
	font-size: 14px;
	line-height: 1.42857143;
	color: #555 !important;
	background-color: #fff !important;
	background-image: none !important;
	border: 1px solid #ccc !important;
	border-radius: 4px !important;
	box-shadow: inset 0 1px 1px rgba(0, 0, 0, .075) !important;
}
</style>
		<h:form prependId="false">
			<h:messages globalOnly="true" styleClass="error" />
			<p:growl id="msg" showDetail="false" />

			<div class="col-md-12" style="margin-bottom: 20px;">
				<div class="col-md-4">
					<div class="form-group">
						<div class="col-md-6">
							<h:outputLabel styleClass="control-label" value="From Date:" />
						</div>
						<div class="col-md-6">
							<p:calendar id="fromDate" value="#{expenseController.fromDate}"
								required="true" requiredMessage="The Date is Empty"
								pattern="dd-MM-yyyy"></p:calendar>
							<h:message for="fromDate" styleClass="error" />
						</div>
					</div>
				</div>

				<div class="col-md-4">
					<div class="form-group">
						<div class="col-md-6">
							<h:outputLabel styleClass="control-label" value="To Date:" />
						</div>
						<div class="col-md-6">
							<p:calendar id="toDate" value="#{expenseController.toDate}"
								required="true" requiredMessage="The Date is Empty"
								pattern="dd-MM-yyyy"></p:calendar>
							<h:message for="toDate" styleClass="error" />
						</div>
					</div>
				</div>
			</div>

			<h:panelGroup id="output-panelGroup">
				<div class="col-md-12" style="margin-bottom: 20px;">

					<div class="col-md-4">

						<div class="form-group">
							<div class="col-md-6">
								<h:outputLabel styleClass="control-label" value="Income:" />
							</div>
							<div class="col-md-6">
								<h:inputText disabled="true" styleClass="form-control"
									value="#{expenseController.income}" />
							</div>
						</div>
					</div>

					<div class="col-md-4">

						<div class="form-group">
							<div class="col-md-6">
								<h:outputLabel styleClass="control-label" value="Expenses:" />
							</div>
							<div class="col-md-6">
								<h:inputText disabled="true" styleClass="form-control"
									value="#{expenseController.expenseSum}" />
							</div>
						</div>

					</div>

					<div class="col-md-4">

						<div class="form-group">
							<div class="col-md-6">
								<h:outputLabel styleClass="control-label" value="Total:" />
							</div>
							<div class="col-md-6">
								<h:inputText disabled="true" styleClass="form-control"
									value="#{expenseController.total}" />
							</div>
						</div>

					</div>


				</div>

				<div class="col-md-12">
					<h:panelGroup id="expenses-panelgroup">
						<p:dataTable id="expensessDataTable" rows="10" paginator="true"
							paginatorTemplate="{CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
							rowsPerPageTemplate="5,10,15,20,50"
							paginatorAlwaysVisible="false" paginatorPosition="bottom"
							value="#{expenseController.allExpenses}" var="expense"
							rowKey="#{expense.id}" rowIndexVar="index" editable="true"
							editMode="cell">

							<p:column id="index" width="50">
								<h:outputText value="#{index+1}"></h:outputText>
							</p:column>

							<p:column id="actions" width="50">
								<h:commandLink styleClass="btn btn-sm btn-danger white"
									action="#{expenseController.selectExpenseForDelete(expense)}"
									onclick="PF('deleteDialogVar').show()">
									<i class="fa fa-trash white" />
									<f:ajax />
								</h:commandLink>
							</p:column>

							<p:column id="type" headerText="Type" filterBy="#{expense.type}"
								sortBy="#{expense.type}" filterMatchMode="contains">

								<p:selectOneMenu value="#{expense.type}" style="width: 100%;">
									<f:selectItem />
									<f:selectItems value="#{expenseController.allExpenseKinds}"
										var="item" itemLabel="#{item.value}" itemValue="#{item.value}" />
								</p:selectOneMenu>
							</p:column>

							<p:column id="value" headerText="Value"
								filterBy="#{expense.value}" sortBy="#{expense.value}"
								filterMatchMode="contains">
								<p:spinner styleClass="text-align-left" value="#{expense.value}"
									stepFactor="0.10" style="width: 100%;" min="0" />
							</p:column>

							<p:column id="date" headerText="Date" sortBy="#{treatment.date}">
								<p:calendar value="#{expense.date}" pattern="dd-MM-yyyy"
									style="width: 100%;" required="true" requiredMessage="Date Is Empty"></p:calendar>
							</p:column>

						</p:dataTable>
					</h:panelGroup>
				</div>
			</h:panelGroup>

			<p:dialog id="deleteDialog" draggable="false" closable="false"
				modal="true" height="50" width="300" resizable="false"
				widgetVar="deleteDialogVar">


				<f:facet name="header">
					<h:outputText value="Confirm Deletion????" />
				</f:facet>

				<h:commandLink value="Ok"
					action="#{expenseController.deleteExpense()}"
					onclick="PF('deleteDialogVar').hide()"
					styleClass="btn btn-primary popup-buttons">
					<f:ajax render="expenses-panelgroup" />
				</h:commandLink>
				<h:commandLink styleClass="btn btn-danger popup-buttons"
					onclick="PF('deleteDialogVar').hide()">
					<h:outputText value="Cancel" />
					<f:ajax />
				</h:commandLink>


			</p:dialog>

			<div class="buttons file-treatments-button">

				<h:commandLink value="Search" action="#{expenseController.search()}"
					styleClass="btn btn-info">
					<f:ajax execute="fromDate toDate" render="output-panelGroup" />
				</h:commandLink>

				<h:commandLink styleClass="btn btn-primary"
					action="#{expenseController.addNewExpense()}">
					<h:outputText value="Add" />
					<f:ajax render="expenses-panelgroup" execute="expenses-panelgroup" />
				</h:commandLink>

				<h:commandLink value="Save" action="#{expenseController.save()}"
					styleClass="btn btn-success">
					<f:ajax execute="expenses-panelgroup" render="msg" />
				</h:commandLink>
			</div>

		</h:form>
	</ui:define>

</ui:composition>

src/main/webapp/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/resources/scaffold/pageTemplate.xhtml">

	<ui:param name="pageTitle" value="Welcome to SYSTEM" />

	<ui:define name="header">
		Welcome to the SYSTEM
	</ui:define>

	<ui:define name="main">
		<h2 class="success">Your application is running.</h2>
	</ui:define>

</ui:composition>